### PR TITLE
Fix #17: Error stream content was not properly redirected

### LINKED ISSUE #17: System.err from a process output is not redirected
We have some tests where the server is failing at startup.

The server is putting the system err logs in its same log file as the normal logs.

But Angela does not correctly redirect the error stream coming from the node process into the server logger, which makes it impossible to distinguish which error comes from which node.

```
    WatchedProcess<TerracottaServerState> watchedProcess = new WatchedProcess<>(new ProcessExecutor()
        .command(createTsaCommand(terracottaServer.getServerSymbolicName(), terracottaServer.getId(), topology, proxiedPorts, installLocation, startUpArgs))
        .directory(installLocation)
        .environment(env)
        .redirectError(System.err)
        .redirectOutput(serverLogOutputStream), stateRef, TerracottaServerState.STOPPED);`
```

Ideally the err stream should be redirected to the `ExternalLoggers.tsaLogger.info(...)`, or in another logger, but still having the same server name prefix (i.e. `[node-1-1]`).

### PR DESCRIPTION
**Pull request by mathieucarbou**
@saurabhagas @aurbroszniowski : what I am trying to achieve is to have both stdout and stderr streamed towards the same location.

### CODE REVIEW

File: common/src/main/java/org/terracotta/angela/common/distribution/Distribution102Controller.java [hunk 1]
```diff
@@ -335,7 +334,6 @@ public TerracottaManagementServerInstanceProcess startTms(File kitDir, File work
         .command(startTmsCommand(kitDir))
         .directory(workingDir)
         .environment(env)
-        .redirectError(System.err)
```
Comment (saurabhagas) [inline common/src/main/java/org/terracotta/angela/common/distribution/Distribution102Controller.java:338]: Won't removing `redirectError(System.err)` mean that we mute the error output?

Comment (mathieucarbou) [reply common/src/main/java/org/terracotta/angela/common/distribution/Distribution102Controller.java:338]: Javadox says that by default the error stream is redirected to the output stream.
But can you double check also to be sure we have the same understanding. Thanks!

Comment (mathieucarbou) [reply common/src/main/java/org/terracotta/angela/common/distribution/Distribution102Controller.java:338]: @saurabhagas : oups! my mistake, I misread. I have updated the PR :-)
